/* Touch-first HSV palette, with equivalent keyboard sliders and editable HEX. */
const EdenColorStudio=(()=>{
  let target='accent',hue=25,sat=20,val=78;
  const labels={accent:'强调色',bg:'页面底色',me:'我的气泡',them:'TA 的气泡'};
  const presets=['#c9b59c','#d9b6bc','#b4bccf','#b5c4b7','#e6d0b2','#d3c2d9','#fbf8f1','#ede8e3','#756e68','#383c47'];
  const read=()=>LS.get('edenCustomColors',{});
  function rgb(h,s,v){s/=100;v/=100;const f=n=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1))));};return '#'+[f(5),f(3),f(1)].map(n=>n.toString(16).padStart(2,'0')).join('');}
  function hsv(hex){const values=hex.match(/[a-f\d]{2}/gi).map(n=>parseInt(n,16)/255);const [r,g,b]=values,max=Math.max(...values),min=Math.min(...values),d=max-min;let h=0;if(d)h=max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4;return [h*60,max?d/max*100:0,max*100];}
  function current(){const c=read();return target==='me'?state.bubbleMeColor||'#f3ebe7':target==='them'?state.bubbleThemColor||'#fffdf8':c[target]||(target==='bg'?'#f7f3ec':'#b79f80');}
  function override(base){const c=read();return {...base,...(c.accent?{accent:c.accent,accent2:c.accent}:{}),...(c.bg?{bg:c.bg}:{}),...(state.bubbleMeColor?{bubble_me:state.bubbleMeColor}:{}),...(state.bubbleThemColor?{bubble_them:state.bubbleThemColor}:{})};}
  function panel(){[hue,sat,val]=hsv(current());const color=rgb(hue,sat,val);return `<section class="ecs sw-card"><div class="ecs-heading"><div><small>COLOUR ATELIER</small><h3>调一抹，属于你的颜色</h3></div><span class="ecs-current" style="background:${color}"></span></div><div class="ecs-targets">${Object.entries(labels).map(([key,label])=>`<button type="button" data-ecs-target="${key}" aria-pressed="${target===key}">${label}</button>`).join('')}</div><div class="ecs-wheel" role="group" aria-label="色相圆环，可触摸选色"><i class="ecs-hue-dot"></i><div class="ecs-sv" aria-label="饱和度与明度选色区"><i class="ecs-sv-dot"></i></div></div><div class="ecs-controls"><label>色相<input data-ecs-slider="h" type="range" min="0" max="359" value="${Math.round(hue)}"></label><label>饱和度<input data-ecs-slider="s" type="range" min="0" max="100" value="${Math.round(sat)}"></label><label>明度<input data-ecs-slider="v" type="range" min="0" max="100" value="${Math.round(val)}"></label></div><div class="ecs-code"><span>HEX</span><input id="ecs-hex" maxlength="7" pattern="#[0-9a-fA-F]{6}" aria-label="十六进制颜色" value="${color}"><button type="button" data-ecs-reset>恢复默认</button></div><div class="ecs-swatches">${presets.map(c=>`<button type="button" data-ecs-swatch="${c}" style="background:${c}" aria-label="选择颜色 ${c}"></button>`).join('')}</div><p class="sw-card-sub">转动色环，轻点中央色板；也可以输入色号。</p></section>`;}
  function paint(){const box=document.querySelector('.ecs');if(!box)return;const color=rgb(hue,sat,val);box.style.setProperty('--ecs-hue',`hsl(${hue} 100% 50%)`);box.style.setProperty('--ecs-angle',hue+'deg');box.style.setProperty('--ecs-x',sat+'%');box.style.setProperty('--ecs-y',(100-val)+'%');box.querySelector('.ecs-current').style.background=color;box.querySelector('#ecs-hex').value=color;for(const [key,value] of [['h',hue],['s',sat],['v',val]])box.querySelector(`[data-ecs-slider="${key}"]`).value=Math.round(value);const preview=document.querySelector('.sw-preview');if(preview){if(target==='bg')preview.style.backgroundColor=color;if(target==='me'||target==='them'){const b=preview.querySelector('.bubble.'+(target==='me'?'me':'them'));if(b)b.style.setProperty('background',color,'important');}}}
  function commit(){const color=rgb(hue,sat,val);if(target==='me'||target==='them'){const key=target==='me'?'bubbleMeColor':'bubbleThemColor';state[key]=color;persist(key);}else LS.set('edenCustomColors',{...read(),[target]:color});applyThemeVars();paint();}
  function mount(){const box=document.querySelector('.ecs');if(!box)return;paint();for(const selector of ['.ecs-wheel','.ecs-sv']){const element=box.querySelector(selector);let dragging=false;const update=e=>{const rect=element.getBoundingClientRect();if(selector==='.ecs-wheel'){const dx=e.clientX-(rect.left+rect.width/2),dy=e.clientY-(rect.top+rect.height/2);hue=(Math.atan2(dy,dx)*180/Math.PI+90+360)%360;}else{sat=Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100));val=100-Math.max(0,Math.min(100,(e.clientY-rect.top)/rect.height*100));}commit();};element.onpointerdown=e=>{if(selector==='.ecs-wheel'&&e.target.closest('.ecs-sv'))return;e.preventDefault();e.stopPropagation();dragging=true;element.setPointerCapture(e.pointerId);update(e);};element.onpointermove=e=>{if(dragging)update(e);};element.onpointerup=element.onpointercancel=()=>{dragging=false;};}box.querySelector('#ecs-hex').onchange=e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value)){[hue,sat,val]=hsv(e.target.value);commit();}else paint();};}
  document.addEventListener('input',event=>{if(event.target.id==='ecs-hex'){if(/^#[0-9a-f]{6}$/i.test(event.target.value)){[hue,sat,val]=hsv(event.target.value);commit();}return;}const key=event.target.dataset.ecsSlider;if(!key)return;if(key==='h')hue=+event.target.value;if(key==='s')sat=+event.target.value;if(key==='v')val=+event.target.value;commit();});
  document.addEventListener('click',event=>{const button=event.target.closest?.('[data-ecs-target],[data-ecs-swatch],[data-ecs-reset]');if(!button)return;if(button.dataset.ecsTarget){target=button.dataset.ecsTarget;const old=document.querySelector('.ecs');old.outerHTML=panel();mount();}else if(button.dataset.ecsSwatch){[hue,sat,val]=hsv(button.dataset.ecsSwatch);commit();}else{LS.set('edenCustomColors',{});state.bubbleMeColor='';state.bubbleThemColor='';persist('bubbleMeColor');persist('bubbleThemColor');render();}});
  return {panel,mount,override,rgb,hsv};
})();
