/* Four Eden-native tables. Cedar owns every rule and legal action. */
const EdenGames=(()=>{
  const names={gomoku:'五子棋',blackjack:'21 点',zhajinhua:'炸金花',mahjong:'红中赖子麻将'};
  const pages={duel_gomoku:'gomoku',duel_blackjack:'blackjack',duel_zhajinhua:'zhajinhua',duel_mahjong:'mahjong'};
  const DEFAULT='http://43.142.110.120/eden';
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let active='',room=null,busy=false,error='',poller=0,requesting=false;
  const config=()=>LS.get('edenServiceConnection',{url:DEFAULT,token:''});
  const saved=()=>LS.get('edenManagedGameRooms',{});
  function base(){const u=new URL(config().url||DEFAULT);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['43.142.110.120','127.0.0.1','localhost'].includes(u.hostname)))throw Error('请填写花园服务地址');return u.href.replace(/\/$/,'');}
  async function call(path,options={}){const c=config();if(!c.token)throw Error('请先填写花园连接码');let response;try{response=await fetch(base()+path,{...options,headers:{Authorization:'Bearer '+c.token,...options.headers},signal:AbortSignal.timeout(35000)});}catch{throw Error('暂时连不上花园服务，请检查网络和地址');}const data=await response.json().catch(()=>({detail:'服务返回了无法读取的数据'}));if(!response.ok)throw Error(data.message||data.detail||`牌室暂时不可用（${response.status}）`);return data.room;}
  function page(game){active=game;room=null;error='';return `<div class="page eg-page">${subHeader(names[game])}<header class="eg-intro"><span class="eg-kicker">THE GARDEN TABLE</span><h1>${names[game]}</h1><p>在花园里，和 Aries 玩一局</p><span class="eg-divider" aria-hidden="true">✧ ─── ✝ ─── ✧</span></header><section id="eg-content" class="eg-content" aria-live="polite"></section></div>`;}
  function afterRender(){const game=pages[state.subPage];if(!game){clearInterval(poller);poller=0;return;}active=game;clearInterval(poller);poller=0;paint();const id=saved()[game];if(id&&config().token)refresh(id);poller=setInterval(()=>{if(state.subPage===`duel_${game}`&&room&&!busy&&!requesting&&room.status==='playing')refresh(room.room_id,true);},2700);}
  function shell(inner){const target=document.getElementById('eg-content');if(!target)return;target.innerHTML=inner;}
  function paint(){if(!config().token){const c=config();shell(`<div class="eg-connect eg-panel"><span class="eg-seal">✝</span><h2>开启花园牌室</h2><p>第一次使用时填写你的 VPS 服务连接码。保存后四个游戏共用。</p><form id="eg-connect-form"><label>服务地址<input name="url" type="url" required value="${escape(c.url||DEFAULT)}"></label><label>连接码<input name="token" type="password" required autocomplete="off" placeholder="花园连接码"></label><button type="submit">连接花园</button></form>${error?`<p class="eg-error">${escape(error)}</p>`:''}</div>`);return;}
    if(!room){shell(`<div class="eg-welcome eg-panel"><span class="eg-seal">✦</span><h2>${names[active]} · 花园牌桌</h2><p>${active==='mahjong'?'你和 Aries 入座，另两席由花园自动补齐。':'你与 Aries 各占一席；轮到 TA 时会自动行动。'}</p><button type="button" data-eg="start" ${busy?'disabled':''}>${busy?'正在开桌…':'开始新的一局'}</button><button type="button" class="eg-text-button" data-eg="settings">修改连接</button>${error?`<p class="eg-error">${escape(error)}</p>`:''}</div>`);return;}
    const me=room.viewer?.player_id||'local-human';const turn=room.current_player_id===me;const actor=room.current_actor?.display_name||'Aries';const finished=['finished','archived','cancelled'].includes(room.status);
    const status=finished?resultText(room,me):turn?'轮到你了':`${actor} 正在想下一步…`;
    let board=active==='gomoku'?gomoku(room,turn):active==='mahjong'?mahjong(room,turn):cards(room,turn);
    shell(`<div class="eg-room-bar"><span class="eg-room-id">ROOM ${escape(room.room_id)}</span><span class="eg-room-status ${turn?'is-turn':''}">${escape(status)}</span></div>${board}<div class="eg-footer"><button type="button" data-eg="new" ${busy?'disabled':''}>再开一局</button><button type="button" data-eg="chat">去和 Aries 聊天</button><button type="button" class="eg-text-button" data-eg="settings">连接设置</button></div>${error?`<p class="eg-error">${escape(error)}</p>`:''}`);
  }
  function resultText(r,me){if(r.winner_player_id)return r.winner_player_id===me?'这一局你赢了 ✧':'这一局 Aries 赢了 ✧';const result=r.board_state?.game_result;if(result?.result_text)return result.result_text;return '这一局结束了 ✧';}
  function people(r){return (r.participants||[]).map(p=>({id:p.player_id,name:p.player_id==='local-human'?'你':p.player_id==='local-ai'?'Aries':p.display_name||'花园友人',turn:r.current_player_id===p.player_id,metadata:p.game_metadata||{}}));}
  function gomoku(r,turn){const board=r.board_state?.board||[];const legal=r.private_state?.legal_actions||[];const legalSet=new Set(legal.map(a=>`${a.row},${a.col}`));const me=(r.participants||[]).find(p=>p.player_id==='local-human');const mine=me?.token;let cells='';for(let row=0;row<15;row++)for(let col=0;col<15;col++){const value=board[row]?.[col];const index=legal.findIndex(a=>a.row===row&&a.col===col);const allowed=turn&&legalSet.has(`${row},${col}`)&&r.status==='playing';cells+=`<button type="button" class="eg-gomoku-cell ${value?'has-stone':''} ${value===mine?'is-mine':''} ${r.board_state?.last_move?.row===row&&r.board_state?.last_move?.col===col?'is-last':''}" ${allowed?`data-eg-action="${index}"`:'disabled'} aria-label="${row+1} 行 ${col+1} 列${value?'，已有棋子':''}">${value?'<i></i>':''}</button>`;}return `<div class="eg-table eg-gomoku"><div class="eg-opponent">${portrait('Aries')}<div><strong>Aries</strong><small>${r.current_player_id==='local-ai'?'正在落子':'等你落子'}</small></div></div><div class="eg-gomoku-board">${cells}</div><div class="eg-player">${portrait('你')}<strong>你</strong><span>五子相连，花园为你作证</span></div></div>`;}
  function portrait(name){return `<span class="eg-portrait" aria-hidden="true">${name==='你'?'♡':'✝'}</span>`;}
  function card(item){if(!item||item.hidden)return '<span class="eg-card is-back"><i>✝</i></span>';const suit=String(item.suit||'');const symbols={spades:'♠',hearts:'♥',diamonds:'♦',clubs:'♣',S:'♠',H:'♥',D:'♦',C:'♣','♠':'♠','♥':'♥','♦':'♦','♣':'♣'};const glyph=symbols[suit]||suit;const red=['♥','♦'].includes(glyph);return `<span class="eg-card ${red?'is-red':''}"><b>${escape(item.rank)}<small>${escape(glyph)}</small></b><em>${escape(glyph)}</em></span>`;}
  function cards(r,turn){const b=r.board_state||{},p=r.private_state||{},players=people(r),me=players.find(x=>x.id==='local-human'),foe=players.find(x=>x.id==='local-ai');const actions=turn?p.legal_actions||[]:[];const buttons=actions.map((a,i)=>`<button type="button" data-eg-action="${i}">${escape(actionLabel(a))}</button>`).join('');if(active==='blackjack'){const dealer=b.dealer||{};return `<div class="eg-table eg-card-table"><div class="eg-dealer"><span class="eg-flourish">✧ 庄家 ✧</span><div class="eg-cards">${(dealer.hand||[]).map(card).join('')}</div><small>${dealer.value?.total??'暗牌未开'}</small></div><div class="eg-card-participants">${[foe,me].filter(Boolean).map(x=>`<div class="eg-card-seat ${x.turn?'is-active':''}">${portrait(x.name)}<strong>${escape(x.name)}</strong><span>${escape(x.metadata.hand_status||'等待')}</span><div class="eg-cards">${(b.players?.[x.id]?.hand||[]).map(card).join('')}</div><small>${b.players?.[x.id]?.value?.total??''} 点</small></div>`).join('')}</div><div class="eg-action-bar">${buttons||'<span>等待牌局更新…</span>'}</div></div>`;}
    return `<div class="eg-table eg-card-table"><div class="eg-pot">✧ 底池 <strong>${escape(b.pot??0)}</strong> ✧</div><div class="eg-card-participants">${[foe,me].filter(Boolean).map(x=>`<div class="eg-card-seat ${x.turn?'is-active':''}">${portrait(x.name)}<strong>${escape(x.name)}</strong><span>${escape(x.metadata.hand_status||'在局中')}</span><div class="eg-cards">${x.id==='local-human'?(p.hand||[]).map(card).join(''):(b.revealed_hands?.[x.id]||[{hidden:true},{hidden:true},{hidden:true}]).map(card).join('')}</div><small>已投入 ${escape(b.players?.[x.id]?.contribution??0)}</small></div>`).join('')}</div>${p.hand_type_label?`<p class="eg-hand-name">${escape(p.hand_type_label)}</p>`:''}<div class="eg-action-bar">${buttons||'<span>等待牌局更新…</span>'}</div></div>`;
  }
  function actionLabel(a){if(a.label)return a.label;return ({hit:'要牌',stand:'停牌',peek:'看牌',call:`跟注 ${a.cost||''}`,raise:`加注 ${a.unit||''}`,compare:'比牌',fold:'弃牌',pass:'过',hu:'胡',peng:'碰',chi:'吃',concealed_gang:'暗杠',added_gang:'加杠',ming_gang:'明杠'})[a.action]||a.kind||a.action||'行动';}
  function tile(t){if(!t||t.back)return '<span class="eg-tile is-back">✧</span>';const suit={W:'万',T:'条',B:'筒',J:'中'}[t.suit]||'';return `<span class="eg-tile ${t.code==='J1'?'is-joker':''}"><b>${escape(t.label||`${t.rank}${suit}`)}</b></span>`;}
  function mahjong(r,turn){const b=r.board_state||{},p=r.private_state||{},persons=people(r),me=persons.find(x=>x.id==='local-human');const others=persons.filter(x=>x.id!=='local-human');const legal=turn?p.legal_actions||[]:[];const actionByTile=new Map(legal.filter(a=>a.kind==='discard').map((a,i)=>[a.action_id.slice(8),legal.indexOf(a)]));const hand=(p.hand||[]).map(t=>{const idx=actionByTile.get(t.id);return `<button type="button" class="eg-hand-tile" ${idx===undefined?'disabled':`data-eg-action="${idx}"`} aria-label="打出${escape(t.label)}">${tile(t)}</button>`;}).join('');const specials=legal.map((a,i)=>a.kind==='discard'?'':`<button type="button" data-eg-action="${i}">${escape(a.label||actionLabel(a))}</button>`).join('');return `<div class="eg-table eg-mahjong"><div class="eg-mahjong-opponents">${others.map(x=>`<div class="eg-mahjong-seat ${x.turn?'is-active':''}">${portrait(x.name)}<strong>${escape(x.name)}</strong><small>${escape(x.metadata.wind||'')}风 · ${x.metadata.hand_count??13} 张</small><div class="eg-mini-tiles">${Array.from({length:Math.min(13,x.metadata.hand_count||13)},()=>'<i></i>').join('')}</div><div class="eg-discard-pool">${(b.discards?.[x.id]||[]).map(tile).join('')}</div></div>`).join('')}</div><div class="eg-mahjong-center"><span>✝</span><strong>${escape(b.round_label||'东一局')}</strong><small>牌山剩余 ${escape(b.wall_remaining??0)} 张</small>${b.last_discard?.tile?`<div class="eg-last-discard">最近打出 ${tile(b.last_discard.tile)}</div>`:''}</div><div class="eg-own-discard">${(b.discards?.['local-human']||[]).map(tile).join('')}</div><div class="eg-own-hand"><div class="eg-own-title"><strong>你的手牌</strong><small>${p.shanten===0?'听牌中':p.shanten>0?`向听 ${p.shanten}`:''}</small></div><div class="eg-hand-tiles">${hand}</div>${p.own_melds?.length?`<div class="eg-melds">${p.own_melds.map(m=>`<span>${m.tiles.map(tile).join('')}</span>`).join('')}</div>`:''}</div><div class="eg-action-bar">${specials||'<span>点手牌即可打出；仅显示服务端允许的动作</span>'}</div></div>`;}
  async function refresh(id,quiet=false){if(requesting)return;requesting=true;try{const next=await call(`/games/rooms/${encodeURIComponent(id)}`);if(active!==next.game_type)return;room=next;error='';paint();}catch(e){if(!quiet){error=e.message;room=null;paint();}}finally{requesting=false;}}
  async function start(){if(busy)return;busy=true;error='';paint();try{room=await call(`/games/${active}/rooms`,{method:'POST'});const all=saved();all[active]=room.room_id;LS.set('edenManagedGameRooms',all);paint();}catch(e){error=e.message;paint();}finally{busy=false;paint();}}
  async function move(index){if(busy||!room)return;const actions=room.private_state?.legal_actions||[];const selected=actions[index];if(!selected||room.current_player_id!=='local-human')return;const move=active==='mahjong'?{action:selected.action,action_id:selected.action_id}:selected;busy=true;error='';try{room=await call(`/games/rooms/${encodeURIComponent(room.room_id)}/move`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({move,revision:room.revision})});paint();}catch(e){error=e.message;paint();}finally{busy=false;}}
  document.addEventListener('click',e=>{const target=e.target.closest?.('[data-eg-action],[data-eg]');if(!target||!target.closest('.eg-page'))return;e.preventDefault();if(target.hasAttribute('data-eg-action')){move(Number(target.dataset.egAction));return;}if(target.dataset.eg==='start'||target.dataset.eg==='new')start();if(target.dataset.eg==='chat')EdenTheme.navigate('chat');if(target.dataset.eg==='settings'){const c=config();room=null;LS.set('edenServiceConnection',{url:c.url,token:''});paint();}});
  document.addEventListener('submit',e=>{if(e.target.id!=='eg-connect-form')return;e.preventDefault();const form=new FormData(e.target);LS.set('edenServiceConnection',{url:String(form.get('url')||DEFAULT).trim().replace(/\/$/,''),token:String(form.get('token')||'').trim()});error='';paint();const id=saved()[active];if(id)refresh(id);});
  return {page,afterRender};
})();
