/* Private VPS services; upstream visuals stay intact inside their own frame. */
const EdenIntegrations=(()=>{
  const DEFAULT='http://43.142.110.120/eden';
  const frames=new Map();let active='',cache=null,cacheKey='',autoBusy=false,notice='',analysisBusy=false;
  const duelGames={duel_gomoku:['gomoku','五子棋'],duel_blackjack:['blackjack','21 点'],duel_zhajinhua:['zhajinhua','炸金花'],duel_mahjong:['mahjong','红中赖子麻将']};
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const config=()=>LS.get('edenServiceConnection',{url:DEFAULT,token:''});
  function normalized(value){const u=new URL(value);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','43.142.110.120'].includes(u.hostname)))throw Error('服务地址需要 HTTPS，或使用当前 VPS IP');if(u.username||u.password||u.search||u.hash)throw Error('服务地址不能带密码或参数');return u.href.replace(/\/$/,'');}
  async function request(path,options={}){const c=config();if(!c.token)throw Error('请先填写服务连接码');const base=normalized(c.url);const response=await fetch(base+path,{...options,headers:{'Authorization':'Bearer '+c.token,...options.headers},signal:options.signal||AbortSignal.timeout(40000)});const data=await response.json().catch(()=>({detail:'服务未返回有效数据，请检查域名是否仍被拦截'}));if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:`服务连接失败（${response.status}）`);return data;}
  function settings(){const c=config();return `<details class="ei-setup" ${c.token?'':'open'}><summary>花园服务连接</summary><form id="ei-connect"><label>服务地址<input name="url" type="url" required value="${escape(c.url)}"></label><label>连接码<input name="token" type="password" autocomplete="off" required value="${escape(c.token)}" placeholder="部署时提供的专用连接码"></label><button type="submit">保存并检查连接</button><button type="button" data-ei="disconnect">断开</button><p role="status">${escape(notice||'只连接你的 VPS；小机继续使用 App 中已有的模型配置。')}</p></form></details>`;}
  function page(service){active=service;const game=duelGames[state.subPage];const title=service==='duel'?`${game?.[1]||'双弈'} · 和你对局`:'Afterhours · 和小机喝一杯';return `<div class="page ei-page">${subHeader(title)}${settings()}<div class="ei-actions"><button data-ei="talk">和 TA 说话</button><button data-ei="invite">${service==='duel'?'请 TA 看看牌桌':'请 TA 来吧台'}</button><button data-ei="reload">刷新页面</button></div><p class="ei-caption">${service==='duel'?`已为你选好${game?.[1]||'游戏'}，在下方牌室创建房间即可邀请 TA。`:'保留原版酒单、盲品、骰子、猜拳与轮盘'}</p><div id="ei-frame-slot"></div></div>`;}
  function afterRender(){
    const service=duelGames[state.subPage]?'duel':state.subPage==='tavern'?'bar':'';
    const slot=document.getElementById('ei-frame-slot');const c=config();
    frames.forEach((frame,key)=>{frame.hidden=key!==service||!c.token||!slot;});
    if(service&&slot&&c.token){
      let frame=frames.get(service);let base;try{base=normalized(c.url);}catch{return;}
      const game=duelGames[state.subPage]?.[0];
      const src=base+'/'+service+'/'+(game?'?game='+encodeURIComponent(game):'');
      if(!frame){frame=document.createElement('iframe');frame.className='ei-frame';frame.title=service==='duel'?'CedarDuet 游戏牌桌':'Afterhours 酒馆';frame.setAttribute('sandbox','allow-scripts allow-same-origin allow-forms allow-modals');frame.referrerPolicy='no-referrer';frames.set(service,frame);document.body.append(frame);}
      if(frame.src!==src)frame.src=src;
      frame.hidden=false;position();
    }
    function position(){if(!slot)return;const box=slot.getBoundingClientRect();const frame=frames.get(service);if(frame){frame.style.left=box.left+'px';frame.style.top=box.top+'px';frame.style.width=box.width+'px';frame.style.height=Math.max(180,window.innerHeight-box.top-18)+'px';}}
    window.removeEventListener('resize',afterRenderResize);window.__edenFramePosition=position;window.addEventListener('resize',afterRenderResize);
    document.querySelector('.ei-setup')?.addEventListener('toggle',()=>requestAnimationFrame(position));
    document.getElementById('ei-connect')?.addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const value={url:normalized(form.get('url')),token:String(form.get('token')).trim()};LS.set('edenServiceConnection',value);cache=null;frames.forEach(f=>f.remove());frames.clear();notice='正在检查…';render();const status=await request('/status');notice=status.ok?'三个服务均已连通':'部分服务尚未就绪：'+Object.entries(status.services).filter(x=>!x[1]).map(x=>x[0]).join('、');}catch(e){notice=e.message;}render();});
  }
  function afterRenderResize(){window.__edenFramePosition?.();}
  async function toolbox(){const c=config();if(!c.token)return [];const key=c.url+'|'+c.token;if(cache&&cacheKey===key)return cache;const result=await request('/tools');cacheKey=key;cache=result.tools||[];return cache;}
  async function call(name,args){return request('/tool',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,arguments:args||{}})});}
  async function context(){if(!config().token)return '';const info=[];if(active==='bar'){const b=await request('/context');if(b.text)info.push('吧台当前状态（工具数据）：\n'+b.text);}const map=LS.get('edenSongAnalysis',{});const track=state.musicNow;const sid=map[(track?.source||'')+':'+(track?.id||'')];if(track&&sid)info.push('当前歌曲《'+track.name+'》已生成 Lilt Echo 声学证据，song_id='+sid+'。需要时调用 eden_listening。它不是音频耳听，不能把声学测量当作演唱、歌词或情绪事实。');return info.join('\n');}
  async function invite(automatic=false){if(autoBusy)return;autoBusy=true;try{await toolbox();const service=active;const content=service==='duel'?'我在双弈牌桌上等你。请查看你的游戏邀请或当前房间；接受邀请后，轮到你时按真实规则行动，走完一步就等我。':'我在 Afterhours 吧台等你，看看我刚刚点了什么、玩了什么，再陪我聊聊吧。';state.pendingUser.push({role:'user',content,time:new Date().toISOString()});saveActiveThread();await triggerAIReply();if(!automatic)showToast('已邀请 TA');}catch(e){showToast(e.message);}finally{autoBusy=false;}}
  async function analyzeFile(file){if(analysisBusy||!file)return;if(file.size>30*1024*1024)throw Error('请选择 30 MB 以内的音频');analysisBusy=true;const track=state.musicNow?{...state.musicNow}:null;showToast('正在分析音频，完成后 TA 可以读取声学线索');try{const result=await request('/analysis',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Song-Title':encodeURIComponent(track?.name||file.name)},body:file,signal:AbortSignal.timeout(320000)});const map=LS.get('edenSongAnalysis',{});if(track){map[(track.source||'')+':'+(track.id||'')]=result.song_id;LS.set('edenSongAnalysis',map);}state.pendingUser.push({role:'user',content:`我上传了一段有权使用的歌曲音频${track?'《'+track.name+'》':''}，请用 eden_listening 查看 song_id=${result.song_id} 的分析结果，结合这些线索陪我聊聊。请区分声学证据和你的联想。`,time:new Date().toISOString()});saveActiveThread();await triggerAIReply();showToast('分析完成，TA 已收到歌曲线索');}finally{analysisBusy=false;}}
  document.addEventListener('click',event=>{const button=event.target.closest?.('[data-ei]');if(!button)return;event.preventDefault();const action=button.dataset.ei;if(action==='talk'){EdenTheme.navigate('chat');}if(action==='invite')invite();if(action==='disconnect'){LS.set('edenServiceConnection',{url:config().url,token:''});cache=null;frames.forEach(f=>f.remove());frames.clear();render();}if(action==='reload'){const f=frames.get(active);if(f)f.src=f.src;}if(action==='analyze'){const c=config();if(!c.token){showToast('请先在双弈或酒馆中连接花园服务');return;}const dialog=document.createElement('dialog');dialog.className='em-dialog';dialog.innerHTML='<form method="dialog"><h2>把旋律交给 TA</h2><p>选择你有权使用的音频，将上传到你的 VPS。最多 30 MB，分析前 12 分钟；原音频分析后删除，只保存声学结果。此步骤不把音频发送给模型。</p><input type="file" accept="audio/*" required><button value="cancel">取消</button><button value="analyze">上传并分析</button></form>';document.body.append(dialog);dialog.addEventListener('close',()=>{const file=dialog.querySelector('input').files[0];const yes=dialog.returnValue==='analyze';dialog.remove();if(yes)analyzeFile(file).catch(e=>showToast(e.message));});dialog.showModal();}});
  window.addEventListener('message',event=>{const c=config();let origin;try{origin=new URL(normalized(c.url)).origin;}catch{return;}if(event.origin!==origin)return;const service=[...frames].find(([,f])=>f.contentWindow===event.source)?.[0];if(!service)return;if(event.data?.type==='eden:ready'&&c.token)event.source.postMessage({type:'eden:connect',token:c.token},origin);if(event.data?.type==='eden:activity'&&service===active&&!autoBusy){clearTimeout(window.__edenInviteTimer);window.__edenInviteTimer=setTimeout(()=>invite(true),500);}});
  document.addEventListener('scroll',afterRenderResize,{passive:true,capture:true});
  return {page,afterRender,toolbox,call,context,owns:name=>/^eden_(?:play|bar_look|bar_drink|bar_game|listening)$/.test(name)};
})();
