const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const front=path.resolve(__dirname,'..'),core=fs.readFileSync(path.join(front,'parts/10_core_all.js'),'utf8');
const response=(status,data)=>({status,ok:status>=200&&status<300,headers:{get:()=> 'application/json'},json:async()=>data,text:async()=>JSON.stringify(data)});
function auth(fetch){const ctx=vm.createContext({state:{musicConfig:{backend:'duetto',token:'old',duettoPin:'1234'}},fetch,musicBase:()=> 'https://music.example',musicBackend:()=> 'duetto',musicHeaders:()=>({}),persist(){},document:{getElementById:()=>null}});vm.runInContext(core.slice(core.indexOf('let musicAuthRefresh'),core.indexOf('/** 把 Duetto')),ctx);vm.runInContext(core.slice(core.indexOf('async function musicDuettoLoginWithPin'),core.indexOf('function ensureAudio')),ctx);return ctx;}
test('concurrent expired tokens renew once and retry with new credentials',async()=>{let logins=0;const ctx=auth(async url=>url.endsWith('/api/auth/status')?response(200,{configured:true}):url.endsWith('/api/auth/login')?(logins++,response(200,{token:'new'})):response(url.includes('token=new')?200:401,{logged:false}));await Promise.all([ctx.musicFetch('/api/ncm/status'),ctx.musicFetch('/api/ncm/status')]);assert.equal(logins,1);assert.equal(ctx.state.musicConfig.token,'new');});
test('successful Netease logged-out response still means valid application PIN',async()=>{let calls=0;const ctx=auth(async()=>{calls++;return response(200,{logged:false});});await ctx.musicDuettoEnsureAuthed();assert.equal(calls,1);});
test('network errors do not trigger PIN login or setup',async()=>{let calls=0;const ctx=auth(async()=>{calls++;throw Error('offline');});await assert.rejects(ctx.musicDuettoEnsureAuthed(),/offline/);assert.equal(calls,1);});
test('rejected PIN preserves server reason and never loops',async()=>{let logins=0;const ctx=auth(async url=>url.endsWith('/api/auth/status')?response(200,{configured:true}):url.endsWith('/api/auth/login')?(logins++,response(401,{error:'PIN incorrect'})):response(401,{}));await assert.rejects(ctx.musicFetch('/api/ncm/status'),/PIN incorrect/);assert.equal(logins,1);assert.equal(ctx.state.musicConfig.token,'old');});
test('setup is used only when server explicitly reports unconfigured',async()=>{const calls=[];const ctx=auth(async url=>{calls.push(url);return url.endsWith('/status')?response(200,{configured:false}):response(200,{token:'first'});});await ctx.musicDuettoLoginWithPin('5678');assert.ok(calls[1].endsWith('/api/auth/setup'));assert.equal(ctx.state.musicConfig.duettoPin,'5678');});
test('typed PIN is captured before QR render removes the input',()=>{const start=core.indexOf('async function musicStartNeteaseQr');const fn=core.slice(start,core.indexOf('try{',start));assert.ok(fn.indexOf('musicCapturePin()')<fn.indexOf('render()'));});
function library(){const writes=[];const ctx=vm.createContext({state:{edenPlaylists:[],chatTarget:'a1'},persist:key=>writes.push(key)});vm.runInContext(fs.readFileSync(path.join(front,'eden/music.js'),'utf8'),ctx);return {api:vm.runInContext('EdenMusic',ctx),ctx,writes};}
test('AI playlist markers persist once, distinct companions keep separate collections',()=>{const {api,ctx,writes}=library();api.remember('雨天|第一首 - A|第二首 - B|第一首 - A');api.remember('雨天|第一首 - A|第二首 - B|第一首 - A');assert.equal(ctx.state.edenPlaylists.length,1);assert.equal(ctx.state.edenPlaylists[0].tracks.length,2);ctx.state.chatTarget='a2';api.remember('雨天|第一首 - A|第二首 - B');assert.equal(ctx.state.edenPlaylists.length,2);assert.deepEqual(writes,['edenPlaylists','edenPlaylists']);});
test('user playlist rejects blank titles and deduplicates tracks by source and id',()=>{const {api,ctx}=library();assert.equal(api.create('  '),null);const p=api.create('我的歌单');api.add(p.id,{id:1,name:'Song',source:'netease',url:'temporary-signed-url'});api.add(p.id,{id:1,name:'Song',source:'netease'});api.add(p.id,{id:1,name:'Other song',source:'spotify'});assert.equal(ctx.state.edenPlaylists[0].tracks.length,2);assert.equal(ctx.state.edenPlaylists[0].tracks[0].url,undefined);});
test('removed themes migrate and sidebar quota is absent',()=>{assert.ok(!core.includes('data-ui-shell="korean"'));assert.ok(!core.includes('data-ui-shell="weibo"'));assert.ok(core.includes('["korean","weibo"].includes(LS.get("uiShell", "classic")) ? "eden"'));assert.ok(!core.includes('class="sb-quota-wrap"'));});
test('inviting enters listening room without sharing a card; sharing is a separate action',()=>{let click,replies=0;const state={uiShell:'eden',chatTarget:'a1',pendingUser:[],messages:[],musicNow:{id:1,name:'测试曲',artists:['歌手']},agents:[],coupleInfo:{}};const ctx=vm.createContext({state,document:{addEventListener:(event,fn)=>{if(event==='click')click=fn;}},EdenTheme:{navigate(){state.subPage=null;state.tab='chat';}},render(){},saveActiveThread(){},triggerAIReply(){replies++;},showToast(){}});vm.runInContext(fs.readFileSync(path.join(front,'eden/music.js'),'utf8'),ctx);const api=vm.runInContext('EdenMusic',ctx);const press=action=>click({target:{closest:()=>({dataset:{em:action}})},preventDefault(){}});press('invite');assert.equal(api.roomActive(),true);assert.equal(replies,1);assert.equal(state.pendingUser[0].song,undefined);assert.match(state.pendingUser[0].content,/邀请/);const html=api.room('<div class="chat-page">existing chat</div>');assert.match(html,/em-duet/);assert.match(html,/existing chat/);press('share');assert.equal(api.roomActive(),false);assert.equal(state.pendingUser[1].song.name,'测试曲');assert.equal(replies,2);});
